# Generated by Django 5.2.7 on 2026-02-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_warehouseemployeesummary_optional_counts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['display_order', 'name'], 'verbose_name': '4. Activity (النشاط)', 'verbose_name_plural': '4. Activities (النشاطات)'},
        ),
        migrations.AlterModelOptions(
            name='businesssystem',
            options={'ordering': ['display_order', 'name'], 'verbose_name': '3. Business System (النظام)', 'verbose_name_plural': '3. Business Systems (الأنظمة)'},
        ),
        migrations.AlterModelOptions(
            name='businessunit',
            options={'ordering': ['display_order', 'name'], 'verbose_name': '2. Business Unit (وحدة الأعمال)', 'verbose_name_plural': '2. Business Units (وحدات الأعمال)'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['display_order', 'name'], 'verbose_name': '1. Status (الحالات)', 'verbose_name_plural': '1. Statuses (الحالات)'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['display_order', 'name'], 'verbose_name': '5. Warehouse (المستودع)', 'verbose_name_plural': '5. Warehouses (المستودعات)'},
        ),
        migrations.AlterModelOptions(
            name='warehousebusinesssystem',
            options={'ordering': ['warehouse', 'display_order'], 'verbose_name': '6. Warehouse Business System (ربط المستودع بالأنظمة)', 'verbose_name_plural': '6. Warehouse Business Systems'},
        ),
        migrations.AlterModelOptions(
            name='warehouseemployeesummary',
            options={'verbose_name': '7. Warehouse Employee Summary (ملخص الموظفين)', 'verbose_name_plural': '7. Warehouse Employee Summaries'},
        ),
        migrations.AlterModelOptions(
            name='warehousephasestatus',
            options={'ordering': ['warehouse', 'display_order', 'business_unit', 'activity'], 'verbose_name': '8. Warehouse Phase Status (حالة المرحلة)', 'verbose_name_plural': '8. Warehouse Phase Statuses'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='رقم الترتيب: الأصغر يظهر أولاً'),
        ),
        migrations.AlterField(
            model_name='businesssystem',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='رقم الترتيب: الأصغر يظهر أولاً'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='رقم الترتيب: الأصغر يظهر أولاً'),
        ),
        migrations.AlterField(
            model_name='status',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='رقم الترتيب: الأصغر يظهر أولاً (0، 1، 2...)'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='ترتيب ظهور الكارد في الصفحة: 1 يظهر أولاً، 2 ثانياً، وهكذا.'),
        ),
    ]
