# Generated by Django 5.2.7 on 2026-02-11 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_whdatarow'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان المرحلة أو السؤال (مثال: Phase 1 details).', max_length=200)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='ترتيب ظهور السكشن: الأصغر يظهر أولاً.')),
                ('is_active', models.BooleanField(default=True, help_text='لو مقفولة مش هتظهر في الواجهة.')),
            ],
            options={
                'verbose_name': 'Phase Section (قسم مرحلة)',
                'verbose_name_plural': 'Phase Sections (أقسام مراحل)',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PhasePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='النص المختصر للنقطة.', max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='ترتيب ظهور النقطة داخل السكشن.')),
                ('section', models.ForeignKey(help_text='المرحلة المرتبطة بالنقطة.', on_delete=django.db.models.deletion.CASCADE, related_name='points', to='dashboard.phasesection')),
            ],
            options={
                'verbose_name': 'Phase Point (نقطة مرحلة)',
                'verbose_name_plural': 'Phase Points (نقاط مراحل)',
                'ordering': ['section', 'display_order', 'id'],
            },
        ),
    ]
