# Generated by Django 5.2.7 on 2026-02-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_phasesection_phasepoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان التوصية (مثال: Enhance Packing List Sheet)', max_length=200)),
                ('description', models.TextField(help_text='وصف التوصية بالتفصيل')),
                ('icon_type', models.CharField(choices=[('check-circle', '✓ Check Circle (توصية منجزة)'), ('scanner', '📟 RF Scanner'), ('people', '👥 People/Team'), ('document', '📄 Document'), ('box', '📦 Box/Package'), ('chart', '📊 Chart/Analytics'), ('settings', '⚙️ Settings'), ('lightbulb', '💡 Lightbulb/Idea'), ('clock', '⏰ Clock/Time'), ('arrow-up', '⬆️ Arrow Up/Improvement'), ('custom', '🖼️ Custom Image')], default='check-circle', help_text='نوع الأيقونة المعروضة بجانب التوصية', max_length=20)),
                ('custom_icon', models.ImageField(blank=True, help_text='صورة مخصصة للأيقونة (فقط لو اخترت Custom Image)', null=True, upload_to='recommendation_icons/')),
                ('icon_bg_color', models.CharField(default='#f5f5f0', help_text='لون خلفية الأيقونة (مثل #f5f5f0)', max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='ترتيب ظهور التوصية: الأصغر يظهر أولاً')),
                ('is_active', models.BooleanField(default=True, help_text='لو مقفولة مش هتظهر في الواجهة')),
            ],
            options={
                'verbose_name': 'Recommendation (توصية)',
                'verbose_name_plural': 'Recommendations (التوصيات)',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
