# Generated by Django 5.2.7 on 2026-02-11 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_recommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['display_order', 'name'], 'verbose_name': '4. Activity', 'verbose_name_plural': '4. Activities'},
        ),
        migrations.AlterModelOptions(
            name='businesssystem',
            options={'ordering': ['display_order', 'name'], 'verbose_name': '3. Business System', 'verbose_name_plural': '3. Business Systems'},
        ),
        migrations.AlterModelOptions(
            name='businessunit',
            options={'ordering': ['display_order', 'name'], 'verbose_name': '2. Business Unit', 'verbose_name_plural': '2. Business Units'},
        ),
        migrations.AlterModelOptions(
            name='dashboardtheme',
            options={'ordering': ['category', 'key'], 'verbose_name': 'Dashboard Theme Color', 'verbose_name_plural': 'Dashboard Theme Colors'},
        ),
        migrations.AlterModelOptions(
            name='phasepoint',
            options={'ordering': ['section', 'display_order', 'id'], 'verbose_name': 'Phase Point', 'verbose_name_plural': 'Phase Points'},
        ),
        migrations.AlterModelOptions(
            name='phasesection',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'Phase Section', 'verbose_name_plural': 'Phase Sections'},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'Recommendation', 'verbose_name_plural': 'Recommendations'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['display_order', 'name'], 'verbose_name': '1. Status', 'verbose_name_plural': '1. Statuses'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['display_order', 'name'], 'verbose_name': '5. Warehouse', 'verbose_name_plural': '5. Warehouses'},
        ),
        migrations.AlterModelOptions(
            name='warehousebusinesssystem',
            options={'ordering': ['warehouse', 'display_order'], 'verbose_name': '6. Warehouse Business System', 'verbose_name_plural': '6. Warehouse Business Systems'},
        ),
        migrations.AlterModelOptions(
            name='warehouseemployeesummary',
            options={'verbose_name': '7. Warehouse Employee Summary', 'verbose_name_plural': '7. Warehouse Employee Summaries'},
        ),
        migrations.AlterModelOptions(
            name='warehousephasestatus',
            options={'ordering': ['warehouse', 'display_order', 'business_unit', 'activity'], 'verbose_name': '8. Warehouse Phase Status', 'verbose_name_plural': '8. Warehouse Phase Statuses'},
        ),
        migrations.AlterModelOptions(
            name='whdatarow',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'WH Data Row', 'verbose_name_plural': 'WH Data Rows'},
        ),
        migrations.AddField(
            model_name='dashboardtheme',
            name='category',
            field=models.CharField(choices=[('tabs', 'Tabs Colors'), ('table', 'Data Table Colors'), ('phases', 'Phases Section Colors'), ('cards', 'Warehouse Cards Colors'), ('general', 'General Colors')], default='general', help_text='Color category for organization', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order: smaller appears first'),
        ),
        migrations.AlterField(
            model_name='businesssystem',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order: smaller appears first'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order: smaller appears first'),
        ),
        migrations.AlterField(
            model_name='dashboardtheme',
            name='description',
            field=models.CharField(blank=True, help_text='Description of what this color controls', max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboardtheme',
            name='key',
            field=models.CharField(help_text='Color key (e.g. tab_active_bg)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dashboardtheme',
            name='value',
            field=models.CharField(blank=True, help_text='Color value (e.g. #4C8FD6)', max_length=200),
        ),
        migrations.AlterField(
            model_name='phasepoint',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Point display order within the section.'),
        ),
        migrations.AlterField(
            model_name='phasepoint',
            name='section',
            field=models.ForeignKey(help_text='The phase this point belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='points', to='dashboard.phasesection'),
        ),
        migrations.AlterField(
            model_name='phasepoint',
            name='text',
            field=models.CharField(help_text='Brief text for the point.', max_length=255),
        ),
        migrations.AlterField(
            model_name='phasesection',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Section display order: smaller appears first.'),
        ),
        migrations.AlterField(
            model_name='phasesection',
            name='is_active',
            field=models.BooleanField(default=True, help_text="If disabled, won't appear in the interface."),
        ),
        migrations.AlterField(
            model_name='phasesection',
            name='title',
            field=models.CharField(help_text='Phase title or question (e.g. Phase 1 details).', max_length=200),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='custom_icon',
            field=models.ImageField(blank=True, help_text='Custom icon image (only if you chose Custom Image)', null=True, upload_to='recommendation_icons/'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=models.TextField(help_text='Detailed recommendation description'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Recommendation display order: smaller appears first'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='icon_bg_color',
            field=models.CharField(default='#f5f5f0', help_text='Icon background color (e.g. #f5f5f0)', max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='icon_type',
            field=models.CharField(choices=[('check-circle', 'Check Circle (Completed)'), ('scanner', 'RF Scanner'), ('people', 'People/Team'), ('document', 'Document'), ('box', 'Box/Package'), ('chart', 'Chart/Analytics'), ('settings', 'Settings'), ('lightbulb', 'Lightbulb/Idea'), ('clock', 'Clock/Time'), ('arrow-up', 'Arrow Up/Improvement'), ('custom', 'Custom Image')], default='check-circle', help_text='Icon type displayed next to the recommendation', max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='is_active',
            field=models.BooleanField(default=True, help_text="If disabled, won't appear in the interface"),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='title',
            field=models.CharField(help_text='Recommendation title (e.g. Enhance Packing List Sheet)', max_length=200),
        ),
        migrations.AlterField(
            model_name='status',
            name='color_hex',
            field=models.CharField(default='#6c757d', help_text='e.g. #2e7d32 for green', max_length=20),
        ),
        migrations.AlterField(
            model_name='status',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order: smaller appears first (0, 1, 2...)'),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_phase_status',
            field=models.BooleanField(default=False, help_text='Used as phase status (Completed, Pending, ...)'),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_warehouse_status',
            field=models.BooleanField(default=True, help_text='Used as warehouse status'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Card display order: 1 appears first, 2 second, etc.'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='phase1_pct',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Phase 1 completion percentage (0-100). Leave blank if not used.', null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='phase2_pct',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Phase 2 completion percentage (0-100). Leave blank if not used.', null=True),
        ),
        migrations.AlterField(
            model_name='warehousebusinesssystem',
            name='system_name_override',
            field=models.CharField(blank=True, help_text='If left blank, system name will be used', max_length=120),
        ),
        migrations.AlterField(
            model_name='warehousebusinesssystem',
            name='system_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('pending_ph1', 'Pending PH1'), ('ph1_completed', 'PH1 completed'), ('pending_ph2', 'Pending PH2'), ('ph2_completed', 'PH2 completed')], help_text='System status: Pending PH1 / PH1 completed / Pending PH2 / PH2 completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='warehouseemployeesummary',
            name='allocated_count',
            field=models.PositiveIntegerField(blank=True, help_text='Optional — leave blank if not needed', null=True),
        ),
        migrations.AlterField(
            model_name='warehouseemployeesummary',
            name='pending_or_edit_count',
            field=models.PositiveIntegerField(blank=True, help_text='Optional — number shown next to pen icon if exists', null=True),
        ),
        migrations.AlterField(
            model_name='warehouseemployeesummary',
            name='phase_label',
            field=models.CharField(blank=True, help_text='e.g. Phase 1', max_length=120),
        ),
        migrations.AlterField(
            model_name='warehouseemployeesummary',
            name='phase_status_label',
            field=models.CharField(blank=True, help_text='e.g. Completed', max_length=120),
        ),
        migrations.AlterField(
            model_name='warehousemetric',
            name='name',
            field=models.CharField(help_text='Display name if not linked to warehouse', max_length=120),
        ),
        migrations.AlterField(
            model_name='whdatarow',
            name='business',
            field=models.ForeignKey(help_text='Business (business unit)', on_delete=django.db.models.deletion.CASCADE, related_name='wh_data_rows_business', to='dashboard.businessunit'),
        ),
        migrations.AlterField(
            model_name='whdatarow',
            name='business_2',
            field=models.ForeignKey(blank=True, help_text='Business 2 (second business unit, optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wh_data_rows_business_2', to='dashboard.businessunit'),
        ),
        migrations.AlterField(
            model_name='whdatarow',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Row order in table'),
        ),
        migrations.AlterField(
            model_name='whdatarow',
            name='emp_no',
            field=models.CharField(help_text='Emp No (numbers)', max_length=50),
        ),
        migrations.AlterField(
            model_name='whdatarow',
            name='wh',
            field=models.CharField(help_text='WH (name)', max_length=120),
        ),
    ]
