# Generated by Django (PhaseSection: days_number, days_label; title blank=True)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0029_potentialchallenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="phasesection",
            name="days_number",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Number on the ribbon (e.g. 30, 60, 90). Enter from Admin.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="phasesection",
            name="days_label",
            field=models.CharField(
                blank=True,
                default="DAYS",
                help_text="Label next to the number (e.g. DAYS).",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="phasesection",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Optional phase title (e.g. Phase 1 details). Used as fallback if Days number is empty.",
                max_length=200,
            ),
        ),
    ]
