# Generated by Django 5.2.7 on 2026-02-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_phasesection_days_number_days_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttrackeritem',
            options={'ordering': ['-start_date', 'display_order', 'id'], 'verbose_name': 'Project Tracker Item', 'verbose_name_plural': 'Project Tracker Items'},
        ),
        migrations.AlterField(
            model_name='phasesection',
            name='title',
            field=models.CharField(blank=True, help_text='Optional phase title (e.g. Phase 1 details). Used as fallback if Days number is empty.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='start_date',
            field=models.DateField(help_text='Project start date (used for month grouping and ordering)'),
        ),
    ]
