# Generated by Django 5.2.7 on 2026-02-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_projecttrackeritem_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='person_name',
            field=models.CharField(help_text='Employee name (person responsible)', max_length=120),
        ),
    ]
