# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_alter_projecttrackeritem_person_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClerkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name_en', models.CharField(db_index=True, help_text='Name shown in sidebar (column DEPT_NAME_EN in Excel)', max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('business', models.CharField(blank=True, max_length=255)),
                ('account', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=64)),
                ('interview_date', models.CharField(blank=True, help_text='e.g. 02.02.2026', max_length=64)),
                ('work_details', models.TextField(blank=True)),
                ('reports_used', models.TextField(blank=True)),
                ('system_badge', models.CharField(blank=True, help_text='Badge/tag e.g. LogFire', max_length=120)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Clerk Detail (Interview Profile)',
                'verbose_name_plural': 'Clerk Details (Interview Profiles)',
                'ordering': ['display_order', 'dept_name_en', 'id'],
            },
        ),
    ]
