# Generated by Django 5.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_clerkdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clerkinterviewtracking',
            name='report_used',
        ),
        migrations.RemoveField(
            model_name='clerkinterviewtracking',
            name='strength',
        ),
    ]
