# Generated by Django 5.2.7 on 2026-03-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_remove_clerkinterviewtracking_report_used_and_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttrackeritem',
            name='department',
            field=models.CharField(blank=True, help_text='Department', max_length=200),
        ),
        migrations.AddField(
            model_name='projecttrackeritem',
            name='remarks',
            field=models.TextField(blank=True, help_text='Remarks'),
        ),
    ]
