# Generated by Django 5.2.7 on 2026-03-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_projecttrackeritem_department_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttrackeritem',
            name='test_deadline_status',
            field=models.CharField(blank=True, choices=[('', 'Not started'), ('done', 'Done'), ('working_on_it', 'Working on it')], default='', help_text='Test Deadline: Not started / Done / Working on it', max_length=20),
        ),
    ]
