# Generated by Django 5.2.7 on 2026-05-09 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_project_register_tw_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='cost_reduction_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost reduction % — توفير تكلفة متوقع كنسبة', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='department',
            field=models.CharField(blank=True, help_text='Department (legacy text; يُفضّل اختيار السجل من القائمة)', max_length=200),
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='department_ref',
            field=models.ForeignKey(blank=True, help_text='Department من قائمة الأدمن', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_projects', to='dashboard.workspacedepartment'),
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='headcount_impact',
            field=models.CharField(blank=True, help_text='Headcount impact (نص حر)', max_length=200),
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approved — موافقة على المشروع'),
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='kpi_success_criteria',
            field=models.TextField(blank=True, help_text='KPI / Success criteria (مثلاً نسبة الهدف)'),
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='objective_sow',
            field=models.TextField(blank=True, help_text='Project Objective / Statement of Work'),
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='person_name',
            field=models.CharField(blank=True, default='', help_text='جهة اتصال ثانية — Project 2 (شخص آخر غير الـ Lead)', max_length=120),
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='project_code',
            field=models.CharField(blank=True, help_text='External project ID / code (e.g. LOG-007)', max_length=80),
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='project_lead',
            field=models.CharField(blank=True, help_text='Team lead (مسؤول التيم)', max_length=120),
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='register_category',
            field=models.ForeignKey(blank=True, help_text='Category من الأدمن', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_projects', to='dashboard.workspaceprojectcategory'),
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='register_priority',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='', help_text='Priority في Project Register', max_length=20),
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='register_status',
            field=models.CharField(blank=True, choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('delayed', 'Delayed'), ('blocked', 'Blocked')], default='', help_text='حالة المشروع في السجل (On Track / …)', max_length=20),
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='scope_deliverables',
            field=models.TextField(blank=True, help_text='Key deliverables'),
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='scope_dependencies',
            field=models.TextField(blank=True, help_text='Dependencies'),
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='scope_in',
            field=models.TextField(blank=True, help_text='In scope'),
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='scope_out',
            field=models.TextField(blank=True, help_text='Out of scope'),
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='sla_improvement',
            field=models.CharField(blank=True, help_text='SLA improvement', max_length=200),
        ),
    ]
