# Generated by Django 5.2.7 on 2026-05-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_executive_overview_kpi_cards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttrackeritem',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Project Tracker Item', 'verbose_name_plural': 'Project Tracker Items'},
        ),
        migrations.AlterField(
            model_name='projecttrackeritem',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='يُحدَّث تلقائياً عند الحفظ: True عندما register_status = Approved'),
        ),
    ]
